### ISSUE TITLE
XSLT2 support

### ISSUE THREAD

**Issue by comp64** [milo/schematron#4]
Hi,
any chances of supporting XSLT2 ? You would gain a reward of having the only PHP solution for validating against XSLT2 schematrons. 
See the exception attached. In case of interest, I'll provide you with both the schematron file and some xmls.

```
PHP Fatal error:  Uncaught Milo\SchematronException: Query binding 'xslt2' is not supported. in /xstest/vendor/milo/schematron/src/Schematron.php:546
Stack trace:
#0 /xstest/vendor/milo/schematron/src/Schematron.php(230): Milo\Schematron->loadSchemaBasics()
#1 /xstest/vendor/milo/schematron/src/Schematron.php(206): Milo\Schematron->loadDom()
#2 /xstest/src/App.php(13): Milo\Schematron->load()
#3 /xstest/src/main.php(5): Comp\App->run()
#4 {main}
  thrown in /home/comp/websupport/xstest/vendor/milo/schematron/src/Schematron.php on line 546
```

**Comment by milo** [comment]
Hi,
todays, I'm upgrading some of my libraries to support PHP 8, Schematron is one of them.
If you are still interested, send me SCH & XML and I'll try that.

**Comment by milo** [comment]
Well, I've done small research - the `xslt2` query binding means that XPath 2 is used. Unfortunately, XPath in current PHP supports only 1.0. So, I'd have to implement XPath 2 functionality and it is overhead for this library.
